# Generated by Django 2.2.5 on 2021-07-13 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0004_person_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
