# Generated by Django 2.2.5 on 2021-07-14 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modal_examples', '0006_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='importance',
            field=models.IntegerField(null=True),
        ),
    ]
