# Generated by Django 2.2.5 on 2021-08-06 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modal_examples', '0007_company_importance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='date_entered',
            field=models.DateField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='tags',
            name='company',
            field=models.ManyToManyField(blank=True, to='modal_examples.Company'),
        ),
    ]
