# Generated by Django 3.2.7 on 2023-06-19 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modal_examples', '0011_note_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
