# Generated by Django 3.2.7 on 2023-07-06 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modal_examples', '0012_note_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='colour',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
